### ISSUE TITLE
relevamiento tecnico

### ISSUE THREAD

**Issue by jorgesosi** [jorgesosi/gestion-cax#2]
donde se va a implementar
donde se ejecutara, cuantos usuarios accederan a mismo tiempo. quienes lo va a ejecutar
como se realizara la actualizacion
tiene que funcinar en la web

**Comment by lucaspassa** [comment]
Vamos a usar Bootstrap HTML y CSS para look and feeld

vamos a usar PHP como lenguaje y vamos a usar MySQL como motor de base de datos
