### ISSUE TITLE
Seguridad de contraseña (encriptado/caracteristicas)

### ISSUE THREAD

**Issue by matiaslavanchi** [jorgesosi/gestion-cax#23]

**Comment by jorgesosi** [comment]
debera implementarse que el usuario este obligado a cambiar la contrasenia despues de su primer acceso, el cuadro de dialogo de la confirmacion debera pedir que reingrese la contrasenia antes de enviarla a la base de datos

**Comment by jorgesosi** [comment]
http://www.w3schools.com/php/func_string_md5.asp

http://php.net/manual/es/function.md5.php
http://www.solingest.com/blog/almacenar-contrasenas-en-mysql

**Comment by jorgesosi** [comment]
se implemeto el sistema de encriptacion y decriptacion  AES,
manteniendo las caracteristicas del proyecto original
